/*
 * This file is generated by jOOQ.
 */
package org.cinema.jooq;


import org.cinema.jooq.tables.FlywaySchemaHistory;
import org.cinema.jooq.tables.Users;


/**
 * Convenience access to all tables in cinema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>cinema.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>cinema.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
