/*
 * This file is generated by jOOQ.
 */
package org.cinema.jooq.tables.records;


import org.cinema.jooq.tables.MovieCategory;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MovieCategoryRecord extends UpdatableRecordImpl<MovieCategoryRecord> implements Record4<Long, byte[], byte[], byte[]> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>cinema.movie_category.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>cinema.movie_category.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>cinema.movie_category.uuid</code>.
     */
    public void setUuid(byte[] value) {
        set(1, value);
    }

    /**
     * Getter for <code>cinema.movie_category.uuid</code>.
     */
    public byte[] getUuid() {
        return (byte[]) get(1);
    }

    /**
     * Setter for <code>cinema.movie_category.movie_uuid</code>.
     */
    public void setMovieUuid(byte[] value) {
        set(2, value);
    }

    /**
     * Getter for <code>cinema.movie_category.movie_uuid</code>.
     */
    public byte[] getMovieUuid() {
        return (byte[]) get(2);
    }

    /**
     * Setter for <code>cinema.movie_category.category_uuid</code>.
     */
    public void setCategoryUuid(byte[] value) {
        set(3, value);
    }

    /**
     * Getter for <code>cinema.movie_category.category_uuid</code>.
     */
    public byte[] getCategoryUuid() {
        return (byte[]) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, byte[], byte[], byte[]> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, byte[], byte[], byte[]> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return MovieCategory.MOVIE_CATEGORY.ID;
    }

    @Override
    public Field<byte[]> field2() {
        return MovieCategory.MOVIE_CATEGORY.UUID;
    }

    @Override
    public Field<byte[]> field3() {
        return MovieCategory.MOVIE_CATEGORY.MOVIE_UUID;
    }

    @Override
    public Field<byte[]> field4() {
        return MovieCategory.MOVIE_CATEGORY.CATEGORY_UUID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public byte[] component2() {
        return getUuid();
    }

    @Override
    public byte[] component3() {
        return getMovieUuid();
    }

    @Override
    public byte[] component4() {
        return getCategoryUuid();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public byte[] value2() {
        return getUuid();
    }

    @Override
    public byte[] value3() {
        return getMovieUuid();
    }

    @Override
    public byte[] value4() {
        return getCategoryUuid();
    }

    @Override
    public MovieCategoryRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public MovieCategoryRecord value2(byte[] value) {
        setUuid(value);
        return this;
    }

    @Override
    public MovieCategoryRecord value3(byte[] value) {
        setMovieUuid(value);
        return this;
    }

    @Override
    public MovieCategoryRecord value4(byte[] value) {
        setCategoryUuid(value);
        return this;
    }

    @Override
    public MovieCategoryRecord values(Long value1, byte[] value2, byte[] value3, byte[] value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MovieCategoryRecord
     */
    public MovieCategoryRecord() {
        super(MovieCategory.MOVIE_CATEGORY);
    }

    /**
     * Create a detached, initialised MovieCategoryRecord
     */
    public MovieCategoryRecord(Long id, byte[] uuid, byte[] movieUuid, byte[] categoryUuid) {
        super(MovieCategory.MOVIE_CATEGORY);

        setId(id);
        setUuid(uuid);
        setMovieUuid(movieUuid);
        setCategoryUuid(categoryUuid);
    }
}
