/*
 * This file is generated by jOOQ.
 */
package org.cinema.jooq.tables.records;


import org.cinema.jooq.tables.MovieFile;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MovieFileRecord extends UpdatableRecordImpl<MovieFileRecord> implements Record4<Long, byte[], byte[], byte[]> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>cinema.movie_file.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>cinema.movie_file.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>cinema.movie_file.uuid</code>.
     */
    public void setUuid(byte[] value) {
        set(1, value);
    }

    /**
     * Getter for <code>cinema.movie_file.uuid</code>.
     */
    public byte[] getUuid() {
        return (byte[]) get(1);
    }

    /**
     * Setter for <code>cinema.movie_file.movie_uuid</code>.
     */
    public void setMovieUuid(byte[] value) {
        set(2, value);
    }

    /**
     * Getter for <code>cinema.movie_file.movie_uuid</code>.
     */
    public byte[] getMovieUuid() {
        return (byte[]) get(2);
    }

    /**
     * Setter for <code>cinema.movie_file.file_uuid</code>.
     */
    public void setFileUuid(byte[] value) {
        set(3, value);
    }

    /**
     * Getter for <code>cinema.movie_file.file_uuid</code>.
     */
    public byte[] getFileUuid() {
        return (byte[]) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, byte[], byte[], byte[]> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, byte[], byte[], byte[]> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return MovieFile.MOVIE_FILE.ID;
    }

    @Override
    public Field<byte[]> field2() {
        return MovieFile.MOVIE_FILE.UUID;
    }

    @Override
    public Field<byte[]> field3() {
        return MovieFile.MOVIE_FILE.MOVIE_UUID;
    }

    @Override
    public Field<byte[]> field4() {
        return MovieFile.MOVIE_FILE.FILE_UUID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public byte[] component2() {
        return getUuid();
    }

    @Override
    public byte[] component3() {
        return getMovieUuid();
    }

    @Override
    public byte[] component4() {
        return getFileUuid();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public byte[] value2() {
        return getUuid();
    }

    @Override
    public byte[] value3() {
        return getMovieUuid();
    }

    @Override
    public byte[] value4() {
        return getFileUuid();
    }

    @Override
    public MovieFileRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public MovieFileRecord value2(byte[] value) {
        setUuid(value);
        return this;
    }

    @Override
    public MovieFileRecord value3(byte[] value) {
        setMovieUuid(value);
        return this;
    }

    @Override
    public MovieFileRecord value4(byte[] value) {
        setFileUuid(value);
        return this;
    }

    @Override
    public MovieFileRecord values(Long value1, byte[] value2, byte[] value3, byte[] value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MovieFileRecord
     */
    public MovieFileRecord() {
        super(MovieFile.MOVIE_FILE);
    }

    /**
     * Create a detached, initialised MovieFileRecord
     */
    public MovieFileRecord(Long id, byte[] uuid, byte[] movieUuid, byte[] fileUuid) {
        super(MovieFile.MOVIE_FILE);

        setId(id);
        setUuid(uuid);
        setMovieUuid(movieUuid);
        setFileUuid(fileUuid);
    }
}
