/*
 * This file is generated by jOOQ.
 */
package org.cinema.jooq.tables.records;


import java.time.LocalDateTime;

import org.cinema.jooq.tables.MoviePublic;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MoviePublicRecord extends UpdatableRecordImpl<MoviePublicRecord> implements Record7<Long, byte[], byte[], byte[], LocalDateTime, LocalDateTime, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>cinema.movie_public.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>cinema.movie_public.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>cinema.movie_public.uuid</code>.
     */
    public void setUuid(byte[] value) {
        set(1, value);
    }

    /**
     * Getter for <code>cinema.movie_public.uuid</code>.
     */
    public byte[] getUuid() {
        return (byte[]) get(1);
    }

    /**
     * Setter for <code>cinema.movie_public.movie_uuid</code>.
     */
    public void setMovieUuid(byte[] value) {
        set(2, value);
    }

    /**
     * Getter for <code>cinema.movie_public.movie_uuid</code>.
     */
    public byte[] getMovieUuid() {
        return (byte[]) get(2);
    }

    /**
     * Setter for <code>cinema.movie_public.branch_uuid</code>.
     */
    public void setBranchUuid(byte[] value) {
        set(3, value);
    }

    /**
     * Getter for <code>cinema.movie_public.branch_uuid</code>.
     */
    public byte[] getBranchUuid() {
        return (byte[]) get(3);
    }

    /**
     * Setter for <code>cinema.movie_public.start_date</code>.
     */
    public void setStartDate(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>cinema.movie_public.start_date</code>.
     */
    public LocalDateTime getStartDate() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>cinema.movie_public.end_date</code>.
     */
    public void setEndDate(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>cinema.movie_public.end_date</code>.
     */
    public LocalDateTime getEndDate() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>cinema.movie_public.total_tickets</code>.
     */
    public void setTotalTickets(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>cinema.movie_public.total_tickets</code>.
     */
    public Integer getTotalTickets() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, byte[], byte[], byte[], LocalDateTime, LocalDateTime, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Long, byte[], byte[], byte[], LocalDateTime, LocalDateTime, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return MoviePublic.MOVIE_PUBLIC.ID;
    }

    @Override
    public Field<byte[]> field2() {
        return MoviePublic.MOVIE_PUBLIC.UUID;
    }

    @Override
    public Field<byte[]> field3() {
        return MoviePublic.MOVIE_PUBLIC.MOVIE_UUID;
    }

    @Override
    public Field<byte[]> field4() {
        return MoviePublic.MOVIE_PUBLIC.BRANCH_UUID;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return MoviePublic.MOVIE_PUBLIC.START_DATE;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return MoviePublic.MOVIE_PUBLIC.END_DATE;
    }

    @Override
    public Field<Integer> field7() {
        return MoviePublic.MOVIE_PUBLIC.TOTAL_TICKETS;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public byte[] component2() {
        return getUuid();
    }

    @Override
    public byte[] component3() {
        return getMovieUuid();
    }

    @Override
    public byte[] component4() {
        return getBranchUuid();
    }

    @Override
    public LocalDateTime component5() {
        return getStartDate();
    }

    @Override
    public LocalDateTime component6() {
        return getEndDate();
    }

    @Override
    public Integer component7() {
        return getTotalTickets();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public byte[] value2() {
        return getUuid();
    }

    @Override
    public byte[] value3() {
        return getMovieUuid();
    }

    @Override
    public byte[] value4() {
        return getBranchUuid();
    }

    @Override
    public LocalDateTime value5() {
        return getStartDate();
    }

    @Override
    public LocalDateTime value6() {
        return getEndDate();
    }

    @Override
    public Integer value7() {
        return getTotalTickets();
    }

    @Override
    public MoviePublicRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public MoviePublicRecord value2(byte[] value) {
        setUuid(value);
        return this;
    }

    @Override
    public MoviePublicRecord value3(byte[] value) {
        setMovieUuid(value);
        return this;
    }

    @Override
    public MoviePublicRecord value4(byte[] value) {
        setBranchUuid(value);
        return this;
    }

    @Override
    public MoviePublicRecord value5(LocalDateTime value) {
        setStartDate(value);
        return this;
    }

    @Override
    public MoviePublicRecord value6(LocalDateTime value) {
        setEndDate(value);
        return this;
    }

    @Override
    public MoviePublicRecord value7(Integer value) {
        setTotalTickets(value);
        return this;
    }

    @Override
    public MoviePublicRecord values(Long value1, byte[] value2, byte[] value3, byte[] value4, LocalDateTime value5, LocalDateTime value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MoviePublicRecord
     */
    public MoviePublicRecord() {
        super(MoviePublic.MOVIE_PUBLIC);
    }

    /**
     * Create a detached, initialised MoviePublicRecord
     */
    public MoviePublicRecord(Long id, byte[] uuid, byte[] movieUuid, byte[] branchUuid, LocalDateTime startDate, LocalDateTime endDate, Integer totalTickets) {
        super(MoviePublic.MOVIE_PUBLIC);

        setId(id);
        setUuid(uuid);
        setMovieUuid(movieUuid);
        setBranchUuid(branchUuid);
        setStartDate(startDate);
        setEndDate(endDate);
        setTotalTickets(totalTickets);
    }
}
